### ISSUE TITLE
Transfer assets using double type amount instead of int type

### ISSUE THREAD

**Issue by joankabello** [RootSoft/algorand-dart#3]
Hello there,

On the method transfer() which is used to transfer assets, i see that the amount is type of **int** instead of **double**. Can this be changed ?
Since when you transfer assets, you would need to transfer a double type like 1.5 for example. But this is not doable since the type specified from the SDK is an int.

Thanks

**Comment by RootSoft** [comment]
Hi Joan 

This issue is actually the same as #2 .
Transactions require the (asset) amount to be [uint64](https://developer.algorand.org/docs/reference/transactions/#asset-transfer-transaction). Because your decimals field is > 0, you have to do some basic math or you can use the format functions:

```final amount = Algo.format(amount,decimals);```

or 

```
(amount * (pow(10, decimals)))
```

**Comment by joankabello** [comment]
Oh okay, i wasn't aware that the **format** method was also for the assets transfer, i thought it was only for the Algos transfers.

My misunderstanding on this one.
Thanks for the explanation!
